[workspace]

members = [
	"pyreunion",
	"reunionjs",
]

[profile.dev]
opt-level = 3

[profile.bench]
debug = true
codegen-units = 1
lto = "fat"

[profile.release]
debug = true
codegen-units = 1
lto = "fat"
opt-level = "s"
